name: Horusec report
on: pull_request

jobs:
  ckecking_code:
    runs-on: ubuntu-latest
    name: Horusec scan
    steps:
      - uses: actions/checkout@v2
      - name: Run Horusec
        id: run_horusec
        uses: fike/horusec-action@v0.1
        with:
          arguments: -p="./" -a="${{ secrets.HORUSEC_TOKEN }}" -u="${{ secrets.HORUSEC_URL }}"  -p .
